name: Deploy Node Image to Github
on:
  workflow_dispatch:
    inputs:
      tag_latest:
        if: ${{ github.ref == 'refs/heads/fix-github-ref-again' }}
        description: 'Tag this docker image as lastest. Should only be used for production releases'
        type: boolean
        default: false

permissions:
  contents: read
  packages: write

jobs:
  Deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Login to Github Registry
        run: echo ${GITHUB_TOKEN} | docker login -u ${GITHUB_USER} --password-stdin ghcr.io
        env:
          GITHUB_USER: ${{ secrets.BREW_GITHUB_USERNAME }}
          GITHUB_TOKEN: ${{ secrets.BREW_GITHUB_TOKEN }}

      - name: Build Node Image
        run: ./ironfish-cli/scripts/build-docker.sh

      - name: Deploy Node Image to Github
        run: ./ironfish-cli/scripts/deploy-docker.sh
        env:
          REGISTRY_URL: ghcr.io/iron-fish
          PACKAGE_NAME: ironfish
          GITHUB_REF_NAME: ${GITHUB_REF_NAME}
          GITHUB_SHA: ${GITHUB_SHA}
          TAG_LATEST: ${{ inputs.tag_latest }}
