name: Deploy Node Image to AWS
on:
  workflow_dispatch:
    inputs:
      tag_latest:
        description: 'Tag this docker image as lastest. Should only be used for production releases'
        type: boolean
        default: false

jobs:
  Deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to AWS Registry
        run: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $AWS_REGISTRY_URL
        env:
          AWS_REGISTRY_URL: ${{ secrets.AWS_NODE_REGISTRY_URL }}

      - name: Build Node Image
        run: ./ironfish-cli/scripts/build-docker.sh

      - name: Deploy Node Image
        run: ./ironfish-cli/scripts/deploy-docker.sh
        env:
          REGISTRY_URL: ${{ secrets.AWS_NODE_REGISTRY_URL }}
          PACKAGE_NAME: ironfish
          GITHUB_REF_NAME: ${GITHUB_REF_NAME}
          GITHUB_SHA: ${GITHUB_SHA}
          TAG_LATEST: ${{ inputs.tag_latest }}
