name: Build @ironfish binaries

on:
  pull_request:
    branches: [ '*' ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        settings:
          - host: macos-latest
            arch: x86_64
            system: apple

          - host: windows-latest
            arch: x86_64
            system: windows

          # requires 20.04 because ironfish depends on openssl 1.1.1, new ubuntu only allows 3.x
          - host: ubuntu-20.04
            arch: x86_64
            system: linux

          # currently no way to build arm64
          # - host: ubuntu-20.04
          #   arch: aarch64
          #   system: linux
          

          # - host: ubuntu-20.04
          #   target: aarch64-apple-darwin

    name: Build ${{ matrix.settings.target }}
    runs-on: ${{ matrix.settings.host }}
    steps:

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.12.1'

      - name: npm init
        run: npm init -y
      
      - name: install dependencies
        run: npm install ironfish caxa@3.0.1

      - name: caxa package
        run: npx caxa --input . --output ${{ matrix.settings.system != 'windows' && 'ironfish' || 'ironfish.exe' }} -- "{{caxa}}/node_modules/.bin/node" "--enable-source-maps" "{{caxa}}/node_modules/ironfish/bin/run"

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.settings.system }}-${{ matrix.settings.arch }}
          path: ${{ matrix.settings.system != 'windows' && 'ironfish' || 'ironfish.exe' }} 
          if-no-files-found: error
